#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

pushd $OPENSHIFT_REPO_DIR > /dev/null

passenger start -a $OPENSHIFT_DIY_IP -p 8080 -d --pid-file \
  $OPENSHIFT_DIY_DIR/run/passenger.pid --log-file \
  $OPENSHIFT_DIY_DIR/logs/app.log
